language: python
python:
- '3.6'
- '3.7'
install: pip install tox-travis
script: tox
notifications:
  webhooks:
    on_success: always
    on_failure: never
    on_start: never
    on_cancel: never
    on_error: never
    if: branch = master
    urls:
      secure: plbognoIR+enq9wMJwMvmtgERnmJ97TFUA+5eqtJKjMz5C1iwdMYhT2jGLaQuD4m/TbrGZiUzim3apDrtY3/vrTOIvUx77x0JM3trcGkTnXcExDqCjSZN/n/ChzC2VRKWWkO+aFyB1y7gdahbKeSKWUdQ39kBelJbxz9dEcadTC46JsMDuBfWvoifzhw5uukh7E8tv+UXRxQlFdsP6QiRzLgD1Bd2aSV8VcOIcjj8Rfm7sNpgz9aa5Mv+prY9D1jj/ndGTiYeC1hbyZXVBFlPlBOiZ1ZHME9dve++Ci3/QBe0jSV8pHYePgRXpz7VbYwrNtMkyogm6dM92lLl79Qk2AFQUlX+MptN5wYHnDvGqYGleVG56eEVdl/001dyngxgD0ydB1Uq+IRGazSV0Me0FuS4u/Nf26rGiMhcpPro5cYgPaTL4NCQgnmw5vh34TM7b/HglGQ3pjNJgb/Dzn+JEs0g6Mz81N2NJLnRkO/2CHdTOoA5PbvPD0WMvAjb4u69mSZQSQQngOJbViD1CYNiFfb/aU9ON41Yu48DboEb+gXLGRzsye6IZWaVfCPHmfJ7yz4Y4BLKLiLWLMkqPhIubaU9vYGrr4qdS9nJE8C4unGn7Qr+M/0BRJoIj8jp6U5BcrvpVVq1c9s9YfB9UQQ8Xt5N6042bxbx3wBuSkt8k8=
